### PR TITLE
removed typo in l.370 HKWorkoheutActivityType

### PR DESCRIPTION
**Pull request by mawarnes**
looks like a typo in line 370

### CODE REVIEW

**Comment by stereoket** [comment]
Does this typo fix allow you to build in the simulator?

**Comment by mawarnes** [comment]
no unfortunately not...I'm guessing it has something to do with the way the module is built...one of the settings in Xcode perhaps? not being able to run in simulator is a major problem as I have no way of debugging to code, perhaps this is a question for the wider titanium community ....help?....stumped!!

**Comment by stereoket** [comment]
Well, it is possible to debug via the console in Xcode or by using a tool like iOSConsole, however it does become a bit of bottleneck in the development process. I will try and research into this a little.

**Comment by mawarnes** [comment]
ok, do you think you might be able to give me a few pointers on how to do that? I've added it into an existing project and it only works when deploying it to a device, in the meantime I'll try and build the module so it works with the simulator.

**Pull request merged**
